run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
  fast: false

linters-settings:
  govet:
    enable-all: false
