run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - examples

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
  fast: false

linters-settings:
  govet:
    enable-all: true
  goimports:
    local-prefixes: github.com/sergiorandria/hsm-go-client
